### ISSUE TITLE
Could not list directories that contain encoded characters after 4e1700960d297d5497a3a1a49794371e6f3f75c6

### ISSUE THREAD

**Issue by LucaGuerra** [rufuspollock/s3-bucket-listing#120]
It looks like a recent patch has stopped `s3-bucket-listing` from displaying contents of directories that contain special characters:  https://github.com/rufuspollock/s3-bucket-listing/commit/4e1700960d297d5497a3a1a49794371e6f3f75c6 

In order to avoid some corner case, the patch encodes path components while creating the S3 query URL. The problem lies in the fact that if we're using s3-bucket-listing to navigate in a directory that contains a special characters, those are already sent encoded in the URL and so will get double encoded before making the query to S3, resulting in an empty directory.

For example, this is our site: https://download.falco.org/?prefix=driver/

Here you can see the bucket listing at the time of writing:
![image](https://github.com/rufuspollock/s3-bucket-listing/assets/35580196/ec401b7f-dbf9-4db5-b112-873e58ab847c)

But clicking in any entry with a plus will result in an encoded URL (such as `?prefix=driver/5.0.1%2Bdriver/`) which will end up being double encoded:
![image](https://github.com/rufuspollock/s3-bucket-listing/assets/35580196/d2111535-4ac1-4787-9d6f-0ccb85ba0aae)

I can think about two fixes for that:
1) revert the patch 4e1700960d297d5497a3a1a49794371e6f3f75c6 , but sadly I do not know which corner cases it was fixing so we would get regressions in some cases;
2) prevent the `prepareTable()` function from encoding directory URLs, but I honestly don't know if browsers would encode those for you either way or if it would create additional issues while creating the href entry.

I can send a PR if you wish, both solutions are very simple but I don't know which would be the best one.

TIA for looking into this and thanks for this script :)

**Comment by rufuspollock** [comment]
Think this is similar to #120. Am looking at this.

**Comment by LucaGuerra** [comment]
Yes, I believe https://github.com/rufuspollock/s3-bucket-listing/issues/121 comes from the same patch and may be because of the same encoding issue. Thanks for looking at this!
