### ISSUE TITLE
Commit 4e1700960d297d5497a3a1a49794371e6f3f75c6 broke our s3 listing site

### ISSUE THREAD

**Issue by ctrepka** [rufuspollock/s3-bucket-listing#121]
Hi there,

Just a heads up that the commit here https://github.com/rufuspollock/s3-bucket-listing/commit/4e1700960d297d5497a3a1a49794371e6f3f75c6 broke our s3 listing site. I don't have time to dig into the peculiar behavior, but the request kept getting resubmitted and was in a continuous loop.

I've forked and rolled back the changes for now which has us back up and running, but I suspect others might begin to report similar behavior.

Thanks for all of your work on this!

**Comment by rufuspollock** [comment]
OK, noted. We may revert that.

**Comment by rufuspollock** [comment]
FIXED in https://github.com/rufuspollock/s3-bucket-listing/commit/b17a2ab6c163df3fb94595777833941799552b5d
