### ISSUE TITLE
Document CORS requirement

### ISSUE THREAD

**Issue by mrdavidlaing** [rufuspollock/s3-bucket-listing#13]
When setting up a [S3 website](http://ci-logsearch-shipper.s3-website-eu-west-1.amazonaws.com/) I found that I needed to add a the following CORS policy for the bucket:

```
<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedMethod>GET</AllowedMethod>
   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
</CORSConfiguration>
```

and grant `Everyone` the `List` and `View` permissions
![screen shot 2014-03-13 at 12 44 16](https://f.cloud.github.com/assets/227505/2409362/46c90dbe-aaad-11e3-9dee-10e967763770.png)

I've documented a full set of setup steps at https://github.com/logsearch/logsearch-shipper.NET/wiki/HOWTO-setup-the-published-builds-S3-bucket

**Comment by rufuspollock** [comment]
@mrdavidlaing good point - would you like to add this to the README instructions and add a pull requst?

**Comment by mrdavidlaing** [comment]
@rgrp Nice bit of delegating there.  PR#14 ready for merging :)
