### ISSUE TITLE
1000 file limit

### ISSUE THREAD

**Issue by RBraxton** [rufuspollock/s3-bucket-listing#16]
Need to extend tool to allow for more than 1000 files.

To get more than 1000 objects, you must make multiple requests using the Marker parameter to tell S3 where you left off for each request.

**Comment by RBraxton** [comment]
When you list the content of a bucket the results come back in blocks (currently 1000 keys or less). If the IsTruncated node is true in the response from Amazon S3, you'll need to make another request to get the rest of your keys. Your code must be prepared to handle this scenario.

If the IsTruncated flag is set, request the next page of results by setting Marker to the value of the NextMarker node from the last Amazon S3 response.

**Comment by pdxfixit** [comment]
FWIW, this issue could probably be closed now.

**Comment by RBraxton** [comment]
Cool!  I ended up writing my own solution back in April.  I didn't have the time or confidence to include it here.  Thanks for coding!
