### ISSUE TITLE
Help to deploy on S3

### ISSUE THREAD

**Issue by tzach** [rufuspollock/s3-bucket-listing#20]
I'm trying to deploy a index.html file on s3 bucket, to list the file on the bucket.
I added the following to the index file:

``` xml
<div id="listing"></div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script>
  var BUCKET_URL='http://s3.amazonaws.com/downloads.osv.io/';
  var S3BL_IGNORE_PATH = true;
</script>
<script src="http://rgrp.github.io/s3-bucket-listing/list.js"></script>
```

and upload the file.
If I use 

``` js
var BUCKET_URL='http://s3.amazonaws.com/downloads.osv.io/';
```

I'm getting a  `No 'Access-Control-Allow-Origin' header is present on the requested resource` from the browser, as the site URL is different then the bucket URL.

If I try 

``` js
var BUCKET_URL='downloads.osv.io.s3-website-us-east-1.amazonaws.com'
```

Nothing is presented

What am I'm missing?

Thanks

**Comment by amitsharma3** [comment]
If you got to https://github.com/rgrp/s3-bucket-listing#s3-website-bucket-permissions . It talks about CORS setting to set for the bucket. Update the CORS setting and use
      var BUCKET_URL='http://s3.amazonaws.com/downloads.osv.io/';

This worked for me.

**Comment by rufuspollock** [comment]
FIXED.
