### ISSUE TITLE
list.js does not work in Chrome with HTTPS EveryWhere

### ISSUE THREAD

**Issue by Atry** [rufuspollock/s3-bucket-listing#23]
If you installed [HTTPS EveryWhere](https://www.eff.org/Https-everywhere), the web page would pop-up a message box `There was an error`.

**Comment by extempl** [comment]
@rgrp Use rawgit.com for true https-served list.js file: https://rawgit.com/rgrp/s3-bucket-listing/gh-pages/list.js

**Comment by rufuspollock** [comment]
@extempl thanks - do you want to a PR on the README?

**Comment by extempl** [comment]
@rgrp https://github.com/rgrp/s3-bucket-listing/pull/57
