### ISSUE TITLE
encodeURIcomponent call on hrefs collapses directory structures into filenames

### ISSUE THREAD

**Issue by ghost** [rufuspollock/s3-bucket-listing#25]
The encodeUIRComponent call added to item.href for files can cause the names of downloaded files to include a dash-separated  full directory path.  This can be seen on the example site, http://data.openspending.org/worldbank/cameroon/.  Select the file Yaounde2.csv file.  The href for this file is **http://data.openspending.org/worldbank%2Fcameroon%2FYaounde2.csv**.  When selected, the file does not download as **Yaounde2.csv**.  Instead, it downloads as **worldbank-cameroon-yaounde2.csv**.

This seems like a potential unintended consequence of escaping other special characters.  Perhaps this was meant to be encodeURI() instead, since item.Key is used as a URL and not a param value in this case.

**Comment by inks007** [comment]
I added an **extra line** in list.js to fix this:

```
// strip off the prefix
item.keyText = item.Key.substring(prefix.length);
if (item.Type === 'directory') {
  if (S3BL_IGNORE_PATH) {
    item.href = location.protocol + '//' + location.hostname + location.pathnam$
  } else {
    item.href = item.keyText;
  }
} else {
  // TODO: need to fix this up for cases where we are on site not bucket
  // in that case href for a file should point to s3 bucket
  item.href = '/' + encodeURIComponent(item.Key);
  // REMOVE %2F from files
  item.href = item.href.replace(/%2F/g,'/');
}
```

You will have to host list.js, until the tweak is merged.
If the JS looks dodge, sorry. I'm new to javascript & GitHub.

**Comment by rufuspollock** [comment]
Can you submit a pull request with this change and then we can merge.
