### ISSUE TITLE
Not working with your downloaded index file

### ISSUE THREAD

**Issue by kaihendry** [rufuspollock/s3-bucket-listing#28]
I uploaded https://raw.githubusercontent.com/rgrp/s3-bucket-listing/gh-pages/index.html to my fastpost test bucket. It doesn't work.

http://fastpost.s3-website-ap-southeast-1.amazonaws.com/
http://fastpost.s3-website-ap-southeast-1.amazonaws.com/parkrun/

**Comment by rufuspollock** [comment]
Is this a website bucket? have you checked https://github.com/rgrp/s3-bucket-listing#s3-website-buckets?

**Comment by kaihendry** [comment]
I've disable Website hosting mode and I get a HTTPS error IIUC https://s3-ap-southeast-1.amazonaws.com/fastpost/index.html

**Comment by rufuspollock** [comment]
@kaihendry but you probably want website bucket hosting - plus you'll need to switch everything to https including API endpoint (see new README instructions updated in last 24h).

**Comment by kaihendry** [comment]
I now have it working, but why isn't able to handle directories? i.e. passed by query or anchor? http://fastpost.s3-website-ap-southeast-1.amazonaws.com/

**Comment by rufuspollock** [comment]
It works fine for us on many sites - see e.g. http://data.openspending.org/

Do you have ACL public for your directory contents?

**Comment by kaihendry** [comment]
I can see it's looking for index.html in every directory since I've setup **Website bucket hosting** as you've recommended... http://fastpost.s3-website-ap-southeast-1.amazonaws.com/parkrun/

So I'm really confused.

**Comment by rufuspollock** [comment]
Ah! I think i may know the problem: you also need to set your error page to be index.html - that way when it gets a 404 on the directory path it will look up index.html - can you try that?

I realize this is not well documented in the README!

**Comment by kaihendry** [comment]
Thanks, finally got it working. http://fastpost.s3-website-ap-southeast-1.amazonaws.com/
