### ISSUE TITLE
Doesn't seem to work if bucket name contains fullstops

### ISSUE THREAD

**Issue by sophiaaar** [rufuspollock/s3-bucket-listing#54]
Hello,

I've had this code working on a bucket with a name like "sophia-test". However, when I made the bucket "test.sophiaexamplebucket.com" and tried to implement the code, the directory appears blank (of course I edited the code according to the instructions)

(note, the bucket names I've used here are purely for examples)

I have seen examples of people using custom URLs/names with fullstops before, so I'm not sure why mine wouldn't be working

Thanks

EDIT: I made an example to show what I'm talking about:

http://sophia.test.bucket.s3-website-eu-west-1.amazonaws.com/

```
<html>
<head>
</head>
<body>
  <div id="listing"></div>
<script>
    var BUCKET_URL = document.location.href.replace(/\/[^\/]+$/, '');
</script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="http://rgrp.github.io/s3-bucket-listing/list.js"></script>
</body>
</html>
```

(I've tried variations of bucketurl/bucketname, and kept them close to the examples. I either end up with Error: [object object], or a blank directory)

**Comment by sophiaaar** [comment]
Oh, in addition, the bucket in question is definitely viewable by everyone, and the files are set to public, too.

**Comment by rufuspollock** [comment]
Can you not set your bucket url explicitly rather than doing the computation:

```
var BUCKET_URL = document.location.href.replace(/\/[^\/]+$/, '');
```

What happens if you set it explicitly?

**Comment by sophiaaar** [comment]
I get the "Error: [object Object]" issue

**Comment by rufuspollock** [comment]
ok - but actually seeing the network traffic for that in your developer console (FF or Chrome) would be super useful ...

**Comment by sophiaaar** [comment]
Like this?

`XMLHttpRequest cannot load http://sophia.test.bucket.s3-eu-west-1.amazonaws.com/?delimiter=/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://sophia.test.bucket.s3-website-eu-west-1.amazonaws.com' is therefore not allowed access.`

**Comment by rufuspollock** [comment]
Yes! So that's your issue - you are having CORs problems because you are making a requests cross-domain. Have you followed the instruction re website stuff carefully - also google cross origin and you'll get lots of info.

**Comment by sophiaaar** [comment]
ah ha!
I changed my CORS config to
`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>`

and now it works! Thank you for your assistance :)
