### ISSUE TITLE
Don't load assets from raw.github.com

### ISSUE THREAD

**Issue by stefanw** [rufuspollock/s3-bucket-listing#6]
1. It's not nice, raw.github.com is not a CDN.
2. It doesn't work anymore, because of [nosniff header taking effect](https://github.com/blog/1482-heads-up-nosniff-header-support-coming-to-chrome-and-firefox)

I've seen this also in some other OKF repos, so heads up.

**Comment by rufuspollock** [comment]
FIXED. Thanks for the heads-up - this seems to be a recent introduction. Fixed in the examples and in our relevant repos.
