### ISSUE TITLE
rgrp.github.io down

### ISSUE THREAD

**Issue by ArturGajowy** [rufuspollock/s3-bucket-listing#60]
Hi!

http://rgrp.github.io/s3-bucket-listing/list.js started giving 404s today. We rely on it in a place or two :)

This is just to let you know - might be an issue for you and others using the script :) I'll switch to my own fork / raw github content

**Comment by ArturGajowy** [comment]
OK I see that it's now available under https://rufuspollock.github.io/s3-bucket-listing/list.js

**Comment by rufuspollock** [comment]
@ArturGajowy hmmm - sorry about this. I thought that github might redirect that. Not sure what I can do other than do redirects and that might be quite complicated.

I note the rawgit links are still working ...

**Comment by ArturGajowy** [comment]
You mentioned in one of the commit messages that rawgit won't work from <script> tags, for some reason. I think it's enough to update the index.html to point to `https://rufuspollock.github.io/s3-bucket-listing/list.js`

**Comment by ArturGajowy** [comment]
Also, please note that https://github.com/rgrp shows no repositories for me

**Comment by rufuspollock** [comment]
@ArturGajowy https://github.com/rgrp  will show no repos since they are all now at https://github.com/rufuspollock (but i have reserved rgrp so no-one "hijacks" it).

**Comment by rufuspollock** [comment]
FIXED.
