### ISSUE TITLE
Used to work but now shows no directory listing of contents or buckets

### ISSUE THREAD

**Issue by munch77** [rufuspollock/s3-bucket-listing#73]
Hi,

I installed this last Christmas, and it has worked great. Client recently used it but it now doesn't show a directory listing. 

Here's the site: http://www.halltech.com.au/

I went and reinstalled with the most recent files. Still nothing. Checked the S3 Settings, they all seem correct, nothing changed. Check the Issues list and went back and checked the configuration. Nothing.

Advice would be greatly appreciated.

Thanks

Chris

**Comment by Tw1ddle** [comment]
Are you sure that the specific files/folders in the bucket have been made public?

One of my buckets looked like yours, and making everything public via the "More->Make public" in the S3 GUI did the trick.

**Comment by munch77** [comment]
Yep. 

Did that again, no such luck.

**Comment by hilchan** [comment]
Just recently downloaded this great solution but seem to be having the same issue as @munch77 sample site where no files or directories are listed and wondering if anyone found a solution.

Thanks,
Hil

**Comment by rufuspollock** [comment]
@hilchan i'd need more detail about what you are experiencing and esp info from the devtools console ...

**Comment by dariachica** [comment]
I am also having issues getting this to work.  Wondering if its me or its something else.  My site looks like munch77's site.  http://minionprod.s3-website-us-east-1.amazonaws.com/ If you need more info please let me know.

-H

**Comment by chitozuka** [comment]
@dariachica u have to set the url of the S3-API(http://minionprod.s3-us-east-1.amazonaws.com/ ), not the site's URL in BACKET_URL(remove -website).

**Comment by tomfrankel** [comment]
1) Set the website to index.html and the 404 error to index.html
2) Load your index.html file to your bucket
3) Add the CORS configuration + bucket policy

If you want a URL which just shows your bucket contents and makes them downloadable...

Make sure the index.html has all variables (var) commented out except var BUCKET_URL.  
Mine is like this and it's working well after 30 mins of playing around with it:

`<script type="text/javascript">
  //var S3BL_IGNORE_PATH = false;
  //var BUCKET_NAME = 'ssi-qc-uploads';
  var BUCKET_URL = 'https://BUCKET-NAME.s3-us-east-2.amazonaws.com';
   //var S3B_ROOT_DIR = '';
   //var S3B_SORT = 'DEFAULT';
  // var EXCLUDE_FILE = 'index.html';
   //var AUTO_TITLE = true;
   //var S3_REGION = 'us-east-2'; // for us-east-1
</script>`

**Comment by idjoo** [comment]
i'm having the same issue here, i notice that when i visit https://minionprod.s3.amazonaws.com/ i get the xml output of the bucket but when i visit mine https://ember.cocatrip.xyz.s3-ap-southeast-1.amazonaws.com/ i get an `Access Denied` error plus saying that the connection is insecure and asked to continue to http site (but i'm guessing @dariachica is using cloudfront maybe? so that the s3 bucket can be accessed using https)

**Comment by rufuspollock** [comment]
INVALID / WONTFIX. I think there isn't an issue per se here but a variety of error scenarios / requests for help.
