### ISSUE TITLE
[Question] Google Storage Bucket

### ISSUE THREAD

**Issue by ghost** [rufuspollock/s3-bucket-listing#85]
Is there any plans to do the same but with a Google Storage Bucket or can someone help me how I can change it to work with it?

**Comment by rufuspollock** [comment]
@PortStone yes it should work. Do you want to have a go and see what happens?

**Comment by ghost** [comment]
Yep

**Comment by rufuspollock** [comment]
FIXED. Please re-open or comment if you found an issue.

**Comment by somm-doe** [comment]
It does work with:  

```
var S3BL_IGNORE_PATH = true;
var BUCKET_NAME = 'xyz';
var BUCKET_URL = 'https://storage.googleapis.com';
```
