### ISSUE TITLE
blank list

### ISSUE THREAD

**Issue by waynemillskidals** [rufuspollock/s3-bucket-listing#86]
Hi

Ive spent some time on this and it keeps returning nothing back? 

the URL of bucket is https://s3greenzone.s3.eu-west-2.amazonaws.com/ . as you can see there is files . showing if going direct to the URL even without adding the zone it works https://s3greenzone.s3.amazonaws.com/

I have added the html file here 
https://www.fuse2.net/greezone/index.html
I have changed all paramaters to different scenarios but nothing is working?

any ideas what i am doing wrong?

Current config is below

```
<!DOCTYPE html>
<html>
<head>
  <title>S3 Bucket Listing Generator</title>
</head>
<body>
  <div id="navigation"></div>
  <div id="listing"></div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
  // var S3BL_IGNORE_PATH = true;
  // var BUCKET_NAME = '';
  // var BUCKET_URL = 'https://s3greenzone.s3.amazonaws.com';
  // var S3B_ROOT_DIR = 'SUBDIR_L1/SUBDIR_L2/';
  // var S3B_SORT = 'NEW2OLD';
  // var EXCLUDE_FILE = 'index.html';  // change to array to exclude multiple files
  // var AUTO_TITLE = true;
  // var S3_REGION = 's3-eu-west-2'; // for us-east-1
</script>
<script type="text/javascript" src="https://rawgit.com/rufuspollock/s3-bucket-listing/gh-pages/list.js"></script>
</body>
</html>
```
CORS and permissions have been set as per your documentation

**Comment by fllyingburritos** [comment]
you need to get rid of the // before each line

**Comment by rufuspollock** [comment]
FIXED.
